Repository hekkaaa/uml-drawing, pull requests merged in 2021-12, with the labels that each got.

#69 Фикс зависимостей библиотеки Logical
  UML_drawing/UML_Logic_Library/UML_Logic_Library.csproj
Labels: bug

#73 WF Build 0.3
  UML_drawing/UML_Drawing/App.config
  UML_drawing/UML_Drawing/Form1.Designer.cs
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Drawing/UML_Drawing.csproj
  UML_drawing/UML_Drawing/ViewForm/CreateForm.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.cs
  UML_drawing/UML_Drawing/ViewForm/SavesInfoFrom.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/SavesInfoFrom.cs
  UML_drawing/UML_Drawing/ViewForm/SavesInfoFrom.resx
  UML_drawing/UML_Drawing/packages.config
  UML_drawing/UML_Logic_Library/UML_Logic_Library.csproj
Labels: bug, backend, UI\UX, Add

#79 WF Build 0.4
  UML_drawing/UML_Database_Library/API/ApiData.cs
  UML_drawing/UML_Drawing/BaseImages/arrow1.png
  UML_drawing/UML_Drawing/BaseImages/arrow2.png
  UML_drawing/UML_Drawing/BaseImages/colors.png
  UML_drawing/UML_Drawing/BaseImages/create.png
  UML_drawing/UML_Drawing/BaseImages/exit.png
  UML_drawing/UML_Drawing/BaseImages/line0.png
  UML_drawing/UML_Drawing/BaseImages/line1.png
  UML_drawing/UML_Drawing/BaseImages/load.png
  UML_drawing/UML_Drawing/BaseImages/object0.png
  UML_drawing/UML_Drawing/BaseImages/object1.png
  UML_drawing/UML_Drawing/BaseImages/object2.png
  UML_drawing/UML_Drawing/BaseImages/rectangle0.png
  UML_drawing/UML_Drawing/BaseImages/rectangle1.png
  UML_drawing/UML_Drawing/BaseImages/rectangle2.png
  UML_drawing/UML_Drawing/BaseImages/save.png
  UML_drawing/UML_Drawing/Form1.Designer.cs
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Drawing/Form1.resx
  UML_drawing/UML_Drawing/ViewForm/CreateForm.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.cs
  UML_drawing/UML_Logic_Library/Handler.cs
Labels: UI\UX, Add

#80 Крохотулечные изменения
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Drawing/MyBoxControl.cs
  UML_drawing/UML_Logic_Library/Markers/SizeMarker.cs
  UML_drawing/UML_Logic_Library/RectangleTwoFields.cs
Labels: UI\UX

#82 fix bug
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Logic_Library/RectangleOneField.cs
Labels: bug, UI\UX

#87 Сделала адекватное изменение текста в формочках
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Drawing/MyBoxControl.cs
  UML_drawing/UML_Drawing/TextBoxOneField.Designer.cs
  UML_drawing/UML_Drawing/TextBoxOneField.cs
  UML_drawing/UML_Drawing/TextBoxOneField.resx
  UML_drawing/UML_Drawing/UML_Drawing.csproj
  UML_drawing/UML_Drawing/ViewForm/TextBoxTwoFields.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/TextBoxTwoFields.cs
  UML_drawing/UML_Drawing/ViewForm/TextBoxTwoFields.resx
  UML_drawing/UML_Logic_Library/PropField.cs
  UML_drawing/UML_Logic_Library/RectangleComponent.cs
  UML_drawing/UML_Logic_Library/RectangleOneField.cs
  UML_drawing/UML_Logic_Library/RectangleTwoFields.cs
  UML_drawing/UML_Logic_Library/SimpleRectangle.cs
Labels: UI\UX, Add

#92 Небольшие работы
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Drawing/MyBoxControl.cs
  UML_drawing/UML_Logic_Library/Arrows/AddictionArrow.cs
  UML_drawing/UML_Logic_Library/Arrows/AgragationArrow.cs
  UML_drawing/UML_Logic_Library/Arrows/AssociationArrow.cs
  UML_drawing/UML_Logic_Library/Arrows/CompozitionArrow.cs
  UML_drawing/UML_Logic_Library/Arrows/InheritanceArrow.cs
  UML_drawing/UML_Logic_Library/Arrows/Line.cs
  UML_drawing/UML_Logic_Library/Arrows/RealizationArrow.cs
  UML_drawing/UML_Logic_Library/Component.cs
  UML_drawing/UML_Logic_Library/Markers/EndLineMarker.cs
  UML_drawing/UML_Logic_Library/Markers/LedgeMarker.cs
  UML_drawing/UML_Logic_Library/UML_Logic_Library.csproj
Labels: refactoring, UI\UX, Fix

#93 Тут все собрано вместе
  UML_drawing/UML_Drawing/BaseImages/icons8-экспорт-50.png
  UML_drawing/UML_Drawing/BaseImages/line2.png
  UML_drawing/UML_Drawing/BaseImages/line3.png
  UML_drawing/UML_Drawing/BaseImages/line4.png
  UML_drawing/UML_Drawing/BaseImages/line5.png
  UML_drawing/UML_Drawing/BaseImages/text.png
  UML_drawing/UML_Drawing/BaseImages/textEdit.png
  UML_drawing/UML_Drawing/Form1.Designer.cs
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Drawing/Form1.resx
  UML_drawing/UML_Drawing/MyBoxControl.cs
  UML_drawing/UML_Drawing/TextBoxOneField.Designer.cs
  UML_drawing/UML_Drawing/TextBoxOneField.cs
  UML_drawing/UML_Drawing/TextBoxOneField.resx
  UML_drawing/UML_Drawing/ViewForm/CreateForm.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.cs
  UML_drawing/UML_Drawing/ViewForm/SavesInfoFrom.cs
  UML_drawing/UML_Drawing/ViewForm/TextBoxTwoFields.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/TextBoxTwoFields.cs
  UML_drawing/UML_Drawing/ViewForm/TextBoxTwoFields.resx
  UML_drawing/UML_Drawing/ViewForm/TextForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/TextForm.cs
  UML_drawing/UML_Drawing/ViewForm/TextForm.resx
  UML_drawing/UML_Logic_Library/AdditionalClasses/Handler.cs
  UML_drawing/UML_Logic_Library/AdditionalClasses/MyGraphicPath.cs
  UML_drawing/UML_Logic_Library/AdditionalClasses/TextField.cs
  UML_drawing/UML_Logic_Library/Arrows/Line.cs
  UML_drawing/UML_Logic_Library/ComponentFactory.cs
  UML_drawing/UML_Logic_Library/ComponentMapper.cs
  UML_drawing/UML_Logic_Library/ComponentRequest.cs
  UML_drawing/UML_Logic_Library/Components.cs
  UML_drawing/UML_Logic_Library/Helpers/GraphicPathHelper.cs
  UML_drawing/UML_Logic_Library/Helpers/PointHelper.cs
  UML_drawing/UML_Logic_Library/Interfaces/IComponent.cs
  UML_drawing/UML_Logic_Library/Interfaces/IHandler.cs
  UML_drawing/UML_Logic_Library/Markers/EndLineMarker.cs
  UML_drawing/UML_Logic_Library/Markers/LedgeMarker.cs
  UML_drawing/UML_Logic_Library/Markers/Marker.cs
  UML_drawing/UML_Logic_Library/Markers/SizeMarker.cs
  UML_drawing/UML_Logic_Library/PropField.cs
  UML_drawing/UML_Logic_Library/RectangleOneField.cs
  UML_drawing/UML_Logic_Library/RectangleTwoFields.cs
  UML_drawing/UML_Logic_Library/Requests/Abstract/IComponentRequest.cs
  UML_drawing/UML_Logic_Library/Requests/BlockRequest.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/Component.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleComponent.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleField.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleOneField.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleTwoFields.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/SimpleRectangle.cs
  UML_drawing/UML_Logic_Library/UML_Logic_Library.csproj
Labels: backend, UI\UX, Add

#97 Загрузка проекта
  UML_drawing/UML_Database_Library/API/ApiData.cs
  UML_drawing/UML_Database_Library/BlackBox/LiveDataElem.cs
  UML_drawing/UML_Database_Library/BlackBox/WorkData.cs
  UML_drawing/UML_Database_Library/BlackBox/WorkJSON.cs
  UML_drawing/UML_Database_Library/UML_Database_Library.csproj
  UML_drawing/UML_Drawing/Form1.Designer.cs
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Drawing/Form1.resx
  UML_drawing/UML_Drawing/MyBoxControl.Designer.cs
  UML_drawing/UML_Drawing/MyBoxControl.cs
  UML_drawing/UML_Drawing/ViewForm/CreateForm.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.cs
  UML_drawing/UML_Logic_Library/AdditionalClasses/Handler.cs
  UML_drawing/UML_Logic_Library/AdditionalClasses/MyGraphicPath.cs
  UML_drawing/UML_Logic_Library/AdditionalClasses/TextField.cs
  UML_drawing/UML_Logic_Library/Arrows/Line.cs
  UML_drawing/UML_Logic_Library/ComponentMapper.cs
  UML_drawing/UML_Logic_Library/Interfaces/IHandler.cs
  UML_drawing/UML_Logic_Library/Markers/EndLineMarker.cs
  UML_drawing/UML_Logic_Library/Markers/LedgeMarker.cs
  UML_drawing/UML_Logic_Library/Markers/Marker.cs
  UML_drawing/UML_Logic_Library/Markers/SizeMarker.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/Component.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleComponent.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleField.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleOneField.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleTwoFields.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/SimpleRectangle.cs
  UML_drawing/UML_Logic_Library/UML_Logic_Library.csproj
  UML_drawing/UML_drawing.sln
Labels: backend, Add

#103 WF Build 0.7 + DB
  UML_drawing/UML_Database_Library/API/ApiData.cs
  UML_drawing/UML_Database_Library/BlackBox/CreateId.cs
  UML_drawing/UML_Database_Library/BlackBox/LiveData.cs
  UML_drawing/UML_Database_Library/BlackBox/LiveDataElem.cs
  UML_drawing/UML_Database_Library/BlackBox/SystemFiles.cs
  UML_drawing/UML_Database_Library/BlackBox/WorkData.cs
  UML_drawing/UML_Database_Library/DataFile/DefaultElem.json
  UML_drawing/UML_Database_Library/DataFile/DefaultProject.json
  UML_drawing/UML_Database_Library/UML_Database_Library.csproj
  UML_drawing/UML_Drawing/Form1.Designer.cs
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Drawing/Form1.resx
  UML_drawing/UML_Drawing/ViewForm/LoadProject.cs
  UML_drawing/UML_Logic_Library/AdditionalClasses/Handler.cs
  UML_drawing/UML_Logic_Library/ComponentMapper.cs
Labels: backend

#109 Add tests in Project
  UML_drawing/TestProject/TestProject.csproj
  UML_drawing/TestProject/UnitTest1.cs
  UML_drawing/TestProject/UnitTestDB.cs
  UML_drawing/UML_Database_Library/API/ApiData.cs
  UML_drawing/UML_drawing.sln
Labels: Remake, Add

#110 Add 8 tests ApiData
  UML_drawing/TestProject/UnitTestDB.cs
  UML_drawing/UML_Database_Library/API/ApiData.cs
  UML_drawing/UML_Database_Library/BlackBox/SystemFiles.cs
  UML_drawing/UML_Database_Library/BlackBox/WorkData.cs
  UML_drawing/UML_drawing.sln
Labels: Add

#112 Начала рефакторить и нашла баги
  UML_drawing/UML_Database_Library/BlackBox/WorkData.cs
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Drawing/MyBoxControl.cs
  UML_drawing/UML_Drawing/ViewForm/CreateForm.cs
  UML_drawing/UML_Drawing/ViewForm/SavesInfoFrom.cs
  UML_drawing/UML_Drawing/ViewForm/TextBoxTwoFields.cs
  UML_drawing/UML_Logic_Library/AdditionalClasses/Handler.cs
  UML_drawing/UML_Logic_Library/Arrows/Arrows.cs
  UML_drawing/UML_Logic_Library/ComponentMapper.cs
  UML_drawing/UML_Logic_Library/Helpers/PointHelper.cs
  UML_drawing/UML_Logic_Library/Interfaces/IComponent.cs
  UML_drawing/UML_Logic_Library/Interfaces/IHandler.cs
  UML_drawing/UML_Logic_Library/Markers/EndLineMarker.cs
  UML_drawing/UML_Logic_Library/Markers/LedgeMarker.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/Component.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleComponent.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleField.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleOneField.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleTwoFields.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/SimpleRectangle.cs
  UML_drawing/UML_Logic_Library/UML_Logic_Library.csproj
Labels: UI\UX, Add, Fix

#115 WF Build 0.8
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Drawing/ViewForm/CreateForm.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.cs
  UML_drawing/UML_Drawing/ViewForm/SavesInfoFrom.cs
  UML_drawing/UML_Drawing/ViewForm/TextBoxTwoFields.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/TextBoxTwoFields.cs
  UML_drawing/UML_Drawing/ViewForm/TextForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/TextForm.cs
  UML_drawing/UML_Logic_Library/AdditionalClasses/Handler.cs
Labels: bug, UI\UX, Add

#118 Тесты и правка багов
  UML_drawing/TestProject/LogicalTest/ArrowsTest.cs
  UML_drawing/TestProject/LogicalTest/ComponentMapperTest.cs
  UML_drawing/TestProject/LogicalTest/MarkersTest.cs
  UML_drawing/TestProject/LogicalTest/Mocks/ComponentMapperMock.cs
  UML_drawing/TestProject/LogicalTest/Mocks/ControlMock.cs
  UML_drawing/TestProject/LogicalTest/SimpleRectangleTest.cs
  UML_drawing/TestProject/TestProject.csproj
  UML_drawing/UML_Database_Library/BlackBox/LiveDataElem.cs
  UML_drawing/UML_Drawing/MainForm.Designer.cs
  UML_drawing/UML_Drawing/MainForm.cs
  UML_drawing/UML_Drawing/MainForm.resx
  UML_drawing/UML_Drawing/MyBoxControl.Designer.cs
  UML_drawing/UML_Drawing/MyBoxControl.cs
  UML_drawing/UML_Drawing/TextBoxOneField.cs
  UML_drawing/UML_Drawing/UML_Drawing.csproj
  UML_drawing/UML_Drawing/ViewForm/LoadProject.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.cs
  UML_drawing/UML_Drawing/ViewForm/SavesInfoFrom.cs
  UML_drawing/UML_Logic_Library/AdditionalClasses/Handler.cs
  UML_drawing/UML_Logic_Library/Arrows/Arrows.cs
  UML_drawing/UML_Logic_Library/ComponentMapper.cs
  UML_drawing/UML_Logic_Library/Interfaces/IComponent.cs
  UML_drawing/UML_Logic_Library/Markers/EndLineMarker.cs
  UML_drawing/UML_Logic_Library/Markers/LedgeMarker.cs
  UML_drawing/UML_Logic_Library/Markers/Marker.cs
  UML_drawing/UML_Logic_Library/Markers/SizeMarker.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/Component.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleComponent.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleField.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleOneField.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleTwoFields.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/SimpleRectangle.cs
  UML_drawing/UML_Logic_Library/UML_Logic_Library.csproj
Labels: backend, refactoring, UI\UX, Add, Fix, Test

#119 + test Handler
  UML_drawing/TestProject/HandlerTest.cs
  UML_drawing/TestProject/UnitTestDB.cs
Labels: Add

#120 WF Build 0.9 alpha
  UML_drawing/TestProject/DBTest/UnitTestDB.cs
  UML_drawing/TestProject/LogicalTest/HandlerTest.cs
  UML_drawing/TestProject/UnitTest1.cs
  UML_drawing/UML_Drawing/UML_Drawing.csproj
  UML_drawing/UML_Drawing/ViewForm/LineForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/LineForm.cs
  UML_drawing/UML_Drawing/ViewForm/LineForm.resx
Labels: bug, refactoring, Test

#123 Мелкие баги
  UML_drawing/UML_Drawing/Canvas/MyBoxControl.Designer.cs
  UML_drawing/UML_Drawing/Canvas/MyBoxControl.cs
  UML_drawing/UML_Drawing/Canvas/MyBoxControl.resx
  UML_drawing/UML_Drawing/MainForm.Designer.cs
  UML_drawing/UML_Drawing/MainForm.cs
  UML_drawing/UML_Drawing/UML_Drawing.csproj
  UML_drawing/UML_Drawing/ViewForm/CreateForm.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxOneField.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxOneField.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxOneField.resx
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxTwoFields.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxTwoFields.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxTwoFields.resx
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextForm.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextForm.resx
Labels: Fix

#124 WF Build 0.9 full
  README.md
  UML_drawing/UML_Drawing/MainForm.cs
  UML_drawing/UML_Drawing/UML_Drawing.csproj
  UML_drawing/UML_Drawing/ViewForm/LoadProject.cs
  UML_drawing/UML_Drawing/ViewForm/ObjectForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/ObjectForm.cs
  UML_drawing/UML_Drawing/ViewForm/ObjectForm.resx
Labels: bug, documentation, UI\UX, Fix

#125 Release 1.2
  README.md
  UML_drawing/TestProject/DBTest/UnitTestDB.cs
  UML_drawing/TestProject/LogicalTest/ArrowsTest.cs
  UML_drawing/TestProject/LogicalTest/ComponentMapperTest.cs
  UML_drawing/TestProject/LogicalTest/HandlerTest.cs
  UML_drawing/TestProject/LogicalTest/MarkersTest.cs
  UML_drawing/TestProject/LogicalTest/Mocks/ComponentMapperMock.cs
  UML_drawing/TestProject/LogicalTest/Mocks/ControlMock.cs
  UML_drawing/TestProject/LogicalTest/SimpleRectangleTest.cs
  UML_drawing/TestProject/TestProject.csproj
  UML_drawing/UML_Database_Library/API/ApiData.cs
  UML_drawing/UML_Database_Library/BlackBox/LiveDataElem.cs
  UML_drawing/UML_Database_Library/BlackBox/SystemFiles.cs
  UML_drawing/UML_Database_Library/BlackBox/WorkData.cs
  UML_drawing/UML_Drawing/Canvas/MyBoxControl.Designer.cs
  UML_drawing/UML_Drawing/Canvas/MyBoxControl.cs
  UML_drawing/UML_Drawing/Canvas/MyBoxControl.resx
  UML_drawing/UML_Drawing/MainForm.Designer.cs
  UML_drawing/UML_Drawing/MainForm.cs
  UML_drawing/UML_Drawing/MainForm.resx
  UML_drawing/UML_Drawing/UML_Drawing.csproj
  UML_drawing/UML_Drawing/ViewForm/CreateForm.cs
  UML_drawing/UML_Drawing/ViewForm/LineForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/LineForm.cs
  UML_drawing/UML_Drawing/ViewForm/LineForm.resx
  UML_drawing/UML_Drawing/ViewForm/LoadProject.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.cs
  UML_drawing/UML_Drawing/ViewForm/ObjectForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/ObjectForm.cs
  UML_drawing/UML_Drawing/ViewForm/ObjectForm.resx
  UML_drawing/UML_Drawing/ViewForm/SavesInfoFrom.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxOneField.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxOneField.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxOneField.resx
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxTwoFields.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxTwoFields.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextBoxTwoFields.resx
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextForm.cs
  UML_drawing/UML_Drawing/ViewForm/TextEditors/TextForm.resx
  UML_drawing/UML_Logic_Library/AdditionalClasses/Handler.cs
  UML_drawing/UML_Logic_Library/Arrows/Arrows.cs
  UML_drawing/UML_Logic_Library/Arrows/Line.cs
  UML_drawing/UML_Logic_Library/ComponentMapper.cs
  UML_drawing/UML_Logic_Library/Helpers/PointHelper.cs
  UML_drawing/UML_Logic_Library/Interfaces/IComponent.cs
  UML_drawing/UML_Logic_Library/Interfaces/IHandler.cs
  UML_drawing/UML_Logic_Library/Markers/EndLineMarker.cs
  UML_drawing/UML_Logic_Library/Markers/LedgeMarker.cs
  UML_drawing/UML_Logic_Library/Markers/Marker.cs
  UML_drawing/UML_Logic_Library/Markers/SizeMarker.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/Component.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleComponent.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleField.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleOneField.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/RectangleTwoFields.cs
  UML_drawing/UML_Logic_Library/StructuralEntities/SimpleRectangle.cs
  UML_drawing/UML_Logic_Library/UML_Logic_Library.csproj
  UML_drawing/UML_drawing.sln
Labels: UI\UX
