Repository hekkaaa/uml-drawing, pull requests merged in 2021-11, with the labels that each got.

#1 Starter project
  README.md
  uml-drawing/.vs/uml-drawing/v17/.suo
  uml-drawing/Database_Library/Class1.cs
  uml-drawing/Database_Library/Database_Library.csproj
  uml-drawing/Database_Library/obj/Database_Library.csproj.nuget.dgspec.json
  uml-drawing/Database_Library/obj/Database_Library.csproj.nuget.g.props
  uml-drawing/Database_Library/obj/Database_Library.csproj.nuget.g.targets
  uml-drawing/Database_Library/obj/Debug/net5.0/.NETCoreApp,Version=v5.0.AssemblyAttributes.cs
  uml-drawing/Database_Library/obj/Debug/net5.0/Database_Library.AssemblyInfo.cs
  uml-drawing/Database_Library/obj/Debug/net5.0/Database_Library.AssemblyInfoInputs.cache
  uml-drawing/Database_Library/obj/Debug/net5.0/Database_Library.GeneratedMSBuildEditorConfig.editorconfig
  uml-drawing/Database_Library/obj/Debug/net5.0/Database_Library.assets.cache
  uml-drawing/Database_Library/obj/project.assets.json
  uml-drawing/Database_Library/obj/project.nuget.cache
  uml-drawing/Logic_Library/Class1.cs
  uml-drawing/Logic_Library/Logic_Library.csproj
  uml-drawing/Logic_Library/obj/Debug/net5.0/.NETCoreApp,Version=v5.0.AssemblyAttributes.cs
  uml-drawing/Logic_Library/obj/Debug/net5.0/Logic_Library.AssemblyInfo.cs
  uml-drawing/Logic_Library/obj/Debug/net5.0/Logic_Library.AssemblyInfoInputs.cache
  uml-drawing/Logic_Library/obj/Debug/net5.0/Logic_Library.GeneratedMSBuildEditorConfig.editorconfig
  uml-drawing/Logic_Library/obj/Debug/net5.0/Logic_Library.assets.cache
  uml-drawing/Logic_Library/obj/Logic_Library.csproj.nuget.dgspec.json
  uml-drawing/Logic_Library/obj/Logic_Library.csproj.nuget.g.props
  uml-drawing/Logic_Library/obj/Logic_Library.csproj.nuget.g.targets
  uml-drawing/Logic_Library/obj/project.assets.json
  uml-drawing/Logic_Library/obj/project.nuget.cache
  uml-drawing/uml-drawing.sln
  uml-drawing/uml-drawing/Form1.Designer.cs
  uml-drawing/uml-drawing/Form1.cs
  uml-drawing/uml-drawing/Program.cs
  uml-drawing/uml-drawing/obj/Debug/net5.0-windows/.NETCoreApp,Version=v5.0.AssemblyAttributes.cs
  uml-drawing/uml-drawing/obj/Debug/net5.0-windows/uml-drawing.AssemblyInfo.cs
  uml-drawing/uml-drawing/obj/Debug/net5.0-windows/uml-drawing.AssemblyInfoInputs.cache
  uml-drawing/uml-drawing/obj/Debug/net5.0-windows/uml-drawing.GeneratedMSBuildEditorConfig.editorconfig
  uml-drawing/uml-drawing/obj/Debug/net5.0-windows/uml-drawing.assets.cache
  uml-drawing/uml-drawing/obj/Debug/net5.0-windows/uml-drawing.csproj.AssemblyReference.cache
  uml-drawing/uml-drawing/obj/project.assets.json
  uml-drawing/uml-drawing/obj/project.nuget.cache
  uml-drawing/uml-drawing/obj/uml-drawing.csproj.nuget.dgspec.json
  uml-drawing/uml-drawing/obj/uml-drawing.csproj.nuget.g.props
  uml-drawing/uml-drawing/obj/uml-drawing.csproj.nuget.g.targets
  uml-drawing/uml-drawing/uml-drawing.csproj
  uml-drawing/uml-drawing/uml-drawing.csproj.user
Labels: documentation

#16 DB Build 0.1
  UML_drawing/UML_Database_Library/API/ApiData.cs
  UML_drawing/UML_Database_Library/BlackBox/LiveData.cs
  UML_drawing/UML_Database_Library/BlackBox/LiveDataElem.cs
  UML_drawing/UML_Database_Library/Class1.cs
  UML_drawing/UML_Database_Library/DataFile/DefaultElem.json
  UML_drawing/UML_Database_Library/UML_Database_Library.csproj
Labels: API, backend

#30 Build 0.2
  UML_drawing/UML_Database_Library/API/ApiData.cs
  UML_drawing/UML_Database_Library/BlackBox/CreateId.cs
  UML_drawing/UML_Database_Library/BlackBox/LiveData.cs
  UML_drawing/UML_Database_Library/BlackBox/WorkJSON.cs
  UML_drawing/UML_Database_Library/DataFile/DefaultProject.json
  UML_drawing/UML_Database_Library/UML_Database_Library.csproj
  UML_drawing/UML_Database_Library/app.config
  UML_drawing/UML_Database_Library/packages.config
Labels: bug, documentation, API, backend

#36 Logic
  UML_drawing/UML_Logic_Library/ArrowComponentRequest.cs
  UML_drawing/UML_Logic_Library/BlockComponent.cs
  UML_drawing/UML_Logic_Library/BlockFields.cs
  UML_drawing/UML_Logic_Library/ComponentFactory.cs
  UML_drawing/UML_Logic_Library/ComponentMapper.cs
  UML_drawing/UML_Logic_Library/ComponentRequest.cs
  UML_drawing/UML_Logic_Library/Handler.cs
  UML_drawing/UML_Logic_Library/Interfaces/IComponent.cs
  UML_drawing/UML_Logic_Library/Interfaces/IHandler.cs
  UML_drawing/UML_Logic_Library/Marker.cs
  UML_drawing/UML_Logic_Library/Requests/Abstract/IBlockComponentRequest.cs
  UML_drawing/UML_Logic_Library/Requests/SingleBlockRequest.cs
  UML_drawing/UML_Logic_Library/SerializableGraphicsPath.cs
  UML_drawing/UML_Logic_Library/SingleBlock.cs
  UML_drawing/UML_Logic_Library/SizeMarker.cs
  UML_drawing/UML_Logic_Library/UML_Logic_Library.csproj
  uml-drawing/.idea/.idea.uml-drawing/.idea/projectSettingsUpdater.xml
  uml-drawing/.idea/.idea.uml-drawing/.idea/workspace.xml
Labels: API, backend

#58 Wf5a38a1c4
  UML_drawing/UML_Database_Library/API/ApiData.cs
  UML_drawing/UML_Drawing/BaseImages/iconprogram.ico
  UML_drawing/UML_Drawing/Form1.Designer.cs
  UML_drawing/UML_Drawing/Form1.cs
  UML_drawing/UML_Drawing/Form1.resx
  UML_drawing/UML_Drawing/InfoForms/AboutBox1.Designer.cs
  UML_drawing/UML_Drawing/InfoForms/AboutBox1.cs
  UML_drawing/UML_Drawing/InfoForms/AboutBox1.resx
  UML_drawing/UML_Drawing/UML_Drawing.csproj
  UML_drawing/UML_Drawing/ViewForm/CreateForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/CreateForm.cs
  UML_drawing/UML_Drawing/ViewForm/CreateForm.resx
  UML_drawing/UML_Drawing/ViewForm/LineForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/LineForm.cs
  UML_drawing/UML_Drawing/ViewForm/LineForm.resx
  UML_drawing/UML_Drawing/ViewForm/LoadProdjectForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProdjectForm.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.cs
  UML_drawing/UML_Drawing/ViewForm/LoadProject.resx
  UML_drawing/UML_Drawing/ViewForm/ObjectForm.Designer.cs
  UML_drawing/UML_Drawing/ViewForm/ObjectForm.cs
  UML_drawing/UML_Drawing/ViewForm/ObjectForm.resx
Labels: UI\UX
